* Introduction
#10книг
 Комментарий к формату. Его простота (рассказать про 10 любимых книг) порождает достаточное количество технических сложностей. 
 Попытки составить подобный список, вспоминая впечатление от всего когда-нибудь прочитанного, похожи на сеанс глубокой психотерапии со сложно прогнозируемым эффектом. Кроме того, ужать завершенный уже в измененном состоянии сознания, колыхающемся, как пламя свечи в зыбкости реальности, список до самых любимых 10 книг это та еще психическая травма. В какой-то момент появилось ощущение, что каждое вычеркивание гасит целую галактику. Вычеркнутый "Доктор Живаго" стал последней каплей и немедленно вернулся к оставшимся в списке 63 книгам. Опыт с 10-ю книгами я повторять больше не буду. Разве что только под наблюдением соответствующего специалиста... 
 Тем не менее построение системы в условиях ограничений, это типичная математическая задача. А сложная задача, это вызов. Поэтому оставить ее без решения, это так же травма. 
 Так среди всех этих травм и родился список из 10 книг. Ни в коем случае не стоит считать его репрезентативной выборкой. Решение состояло в том, что бы сконструировать набор из 10 книг случайным образом из списка горячо любимых. 
 Однако поскольку полученный набор порожден именно этим списком, то все, о чем я буду писать, так или иначе произвело на меня достаточно сильное впечатление. Именно так и прошу к написанному относиться. И, безусловно, эти книги рекомендую. 
* Волшебная зима. Туве Янсен
Удивительная прекрасная, добрая и немного жестокая, как сама жизнь, сказка. Непередаваемое ощущение холодного сияния скандинавской зимы, льющееся со страниц книги. Тепло жизни среди леденящего холода ощущается особенно остро. 

"– Что это за песенка? – спросил Муми-тролль.

– Это песенка обо мне, – ответили из ямки. – Песенка про Туу-тикки, которая сложила из снежков снежный фонарь, но в припеве говорится совсем о другом.

– Понятно, – сказал Муми-тролль и сел прямо в снег.

– Ничего тебе не понятно, – дружелюбно произнесла Туу-тикки и высунулась из ямки, так что стала видна ее куртка в красно-белую полоску. – Потому что в припеве говорится как раз о том, чего нельзя понять. А я думаю сейчас о северном сиянии. Неизвестно, есть оно на самом деле или это одна видимость. Все очень неопределенно, и это-то меня и успокаивает."

Вся серия про мумми-троллепй рекомендуется к прочтению. Но волшебную зиму я люблю особенно.
* Человек-ящик. Кобо Абэ
* Пикник на обочине, Стругацкие
* Солярис, Лем
* Час Быка, Ефремов
* И-Цзин, Щуцкий
* Игрок, Достоевский
* Шум и ярость, Фолкнер
* Великий Гэтсби, Фицджеральд
* Хроники хищных городов, Рив
* Вокзал потерянных снов, Мьевиль
* Каста огня, Фехевари
* Газдрубал, Чапек
* Приключения бравого солдата Швейка, Гашек
* Над пропастью во ржи, Сэлинджер 
* Никогде, Гейман
* Приключения Алисы, Керрол
* Трое в лодке не считая собаки, Джером К. Джером
* Записки о Шерлоке Холмсе, Дойл
* Бойня номер 5, Воннегут
* В основном безвредна, Адамс
* Моби Дик, Мелвилл
* Приключения Тома Сойера, Твен
* Айвенго, Скотт
* Повелитель мух, Голдинг
* Снятся ли андроидам электроовцы, Дик
* Джейн Эйр, Бронте
* Одиссея, Гомер
* Ад, Данте
* Гаргантюа и Пантагрюэль, Рабле
* Путешествия Гулливера, Свифт
* Лолита, Набоков
* Дон Кихот, Сервантес
* «1984», Оруэлл
* Бегущий за ветром, Хоссейни
* Полковнику никто не пишет, Маркес
* Старик и Море, Хемингуэй
* Три товарища, Ремарк
* Снежная королева, Андерсен
* Тысяча и одна ночь
* Не отпускай меня, Исигуро
* Норвежский лес, Мураками
* Тихий Дон, ?
* Слово о полку Игореве
* Винни-Пух и все-все-все, Милн
* Малыш и Карлсон, Линдгрен
* Исповедь, Августин А.
* Элементарная математика с точки зрения высшей, Клейн
* Мир компьютеров, Хасэгава
* Пангеометрия, Лобачевский
* Коловращение, О'Генри
* Маугли, Киплинг
