* Боевые искусства
Заниматься боевыми искусствами это круть-крутецкая. Есть конечно мнение, что так себе это занятие, негативно влияет на умственные кондиции. Что, конечно, несусветная чушь. Бойцовский интеллект, это, в первую очередь, про интеллект. Да, надо отдавать себе отчет, чем ты занимаешься. Есть вещи, безусловно вредные для мозга. Но бой с тенью, скакалка и отработка гипер-реакции на пневмо-груше ничего плохого вашему мозгу не сделают, а, наоброт, добавят новых нейронных связей. Да, регулярная акцентированная работа на тяжелом мешке вредна. Микросотресения - это не про здоровье мозга. Сведите ее к минимуму. Это упражнение многие любят, несмотря на его вред и относительную бессмысленность. Сильный удар, это прежде всего техника и координация и тяжелый мешок вовсе не основа его постановки. Хотя дозированная работа с ним допустима и дает определенные результаты, особенно в работе ног. Насчет пропускать удары в голову. Тут даже и обсуждать особо нечего. Это вредно. И  если это происходит регулярно, то что-то не так в вашем тренировочном процессе, пересмотрите его. Не стыдно отказаться от спаринга с превосходящим вас соперником, решившим по какой-то причине накидать вам в голову. Стыдно потом долго и безуспешно подбирать простые слова в разговоре. Растите постепенно, не форсируя развитие ценой травм. Возможно вы еще вернетесь к прерваному вами спортивному спору, но уже совсем на других условиях. Тренировочный обмен ударами двух бойцов одинакового высокого уровня намного менее травмоопасен, чем "обучение" нуба неадекватным более опытным соперником или хаотический обмен ударами двух новичков. Правило простое, учимся, растем, а потом уже спаринги.         
